loteria = "https://noticias.uol.com.br/loterias/"
steamLink = "https://store.steampowered.com/"
steamAPIUrl = "https://store.steampowered.com/api/featuredcategories?cc=br&?l=brazilian"
cinema10 = "https://cinema10.com.br/cartaz"
udemy = "https://www.discudemy.com/all"
defUrl = "https://dicio-api-ten.vercel.app/"
shortUrl = "https://short-link-api.vercel.app/"